apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: adservice
spec:
  params:
  - name: APP_NAME
    value: adservice
  - name: GIT_REPO
    value: https://github.com/noseka1/red-hat-gallery
  - name: GIT_REVISION
    value: red-hat-gallery
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc.cluster.local:5000/gallery/adservice:latest
  - name: PATH_CONTEXT
    value: ./src/adservice
  pipelineRef:
    name: adservice
  serviceAccountName: pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
