apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cartservice
spec:
  params:
  - name: APP_NAME
    type: string
    default: cartservice
  - name: GIT_REPO
    type: string
    default: https://github.com/noseka1/red-hat-gallery
  - name: GIT_REVISION
    type: string
    default: red-hat-gallery
  - name: IMAGE_NAME
    type: string
    default: image-registry.openshift-image-registry.svc.cluster.local:5000/gallery/cartservice:latest
  - name: PATH_CONTEXT
    type: string
    default: ./src/cartservice/src
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: TLSVERIFY
      value: "false"
    - name: CONTEXT
      value: $(params.PATH_CONTEXT)
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: deploy
    params:
    - name: SCRIPT
      value: oc rollout restart deploy/$(params.APP_NAME)
    runAfter:
    - build
    taskRef:
      kind: ClusterTask
      name: openshift-client
  workspaces:
  - name: workspace
