apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: checkoutservice
spec:
  params:
  - name: APP_NAME
    value: checkoutservice
  - name: GIT_REPO
    value: https://github.com/stratus-ss/red-hat-gallery
  - name: GIT_REVISION
    value: red-hat-gallery
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc.cluster.local:5000/gallery/checkoutservice:latest
  - name: PATH_CONTEXT
    value: ./src/checkoutservice
  pipelineRef:
    name: checkoutservice
  serviceAccountName: pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
