apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: currencyservice
spec:
  params:
  - name: APP_NAME
    value: currencyservice
  - name: GIT_REPO
    value: https://github.com/noseka1/red-hat-gallery
  - name: GIT_REVISION
    value: red-hat-gallery
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc.cluster.local:5000/gallery/currencyservice:latest
  - name: PATH_CONTEXT
    value: ./src/currencyservice
  pipelineRef:
    name: currencyservice
  serviceAccountName: pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
