apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gallery

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: NAMESPACE
  objref:
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    name: grafana

resources:
- grafana-og.yaml
- grafana-sub.yaml

configurations:
- kustomizeconfig.yaml
